# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class KNSDay2Actions(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, member_vnf_index: str=None, kdu_name: str=None, additional_params: object=None):  # noqa: E501
        """KNSDay2Actions - a model defined in Swagger

        :param member_vnf_index: The member_vnf_index of this KNSDay2Actions.  # noqa: E501
        :type member_vnf_index: str
        :param kdu_name: The kdu_name of this KNSDay2Actions.  # noqa: E501
        :type kdu_name: str
        :param additional_params: The additional_params of this KNSDay2Actions.  # noqa: E501
        :type additional_params: object
        """
        self.swagger_types = {
            'member_vnf_index': str,
            'kdu_name': str,
            'additional_params': object
        }

        self.attribute_map = {
            'member_vnf_index': 'member-vnf-index',
            'kdu_name': 'kdu-name',
            'additional_params': 'additional_params'
        }
        self._member_vnf_index = member_vnf_index
        self._kdu_name = kdu_name
        self._additional_params = additional_params

    @classmethod
    def from_dict(cls, dikt) -> 'KNSDay2Actions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The KNSDay2Actions of this KNSDay2Actions.  # noqa: E501
        :rtype: KNSDay2Actions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def member_vnf_index(self) -> str:
        """Gets the member_vnf_index of this KNSDay2Actions.


        :return: The member_vnf_index of this KNSDay2Actions.
        :rtype: str
        """
        return self._member_vnf_index

    @member_vnf_index.setter
    def member_vnf_index(self, member_vnf_index: str):
        """Sets the member_vnf_index of this KNSDay2Actions.


        :param member_vnf_index: The member_vnf_index of this KNSDay2Actions.
        :type member_vnf_index: str
        """
        if member_vnf_index is None:
            raise ValueError("Invalid value for `member_vnf_index`, must not be `None`")  # noqa: E501

        self._member_vnf_index = member_vnf_index

    @property
    def kdu_name(self) -> str:
        """Gets the kdu_name of this KNSDay2Actions.


        :return: The kdu_name of this KNSDay2Actions.
        :rtype: str
        """
        return self._kdu_name

    @kdu_name.setter
    def kdu_name(self, kdu_name: str):
        """Sets the kdu_name of this KNSDay2Actions.


        :param kdu_name: The kdu_name of this KNSDay2Actions.
        :type kdu_name: str
        """
        if kdu_name is None:
            raise ValueError("Invalid value for `kdu_name`, must not be `None`")  # noqa: E501

        self._kdu_name = kdu_name

    @property
    def additional_params(self) -> object:
        """Gets the additional_params of this KNSDay2Actions.


        :return: The additional_params of this KNSDay2Actions.
        :rtype: object
        """
        return self._additional_params

    @additional_params.setter
    def additional_params(self, additional_params: object):
        """Sets the additional_params of this KNSDay2Actions.


        :param additional_params: The additional_params of this KNSDay2Actions.
        :type additional_params: object
        """

        self._additional_params = additional_params
