# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ScaleHorizontal(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, replicas_number: int=None):  # noqa: E501
        """ScaleHorizontal - a model defined in Swagger

        :param replicas_number: The replicas_number of this ScaleHorizontal.  # noqa: E501
        :type replicas_number: int
        """
        self.swagger_types = {
            'replicas_number': int
        }

        self.attribute_map = {
            'replicas_number': 'replicas_number'
        }
        self._replicas_number = replicas_number

    @classmethod
    def from_dict(cls, dikt) -> 'ScaleHorizontal':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScaleHorizontal of this ScaleHorizontal.  # noqa: E501
        :rtype: ScaleHorizontal
        """
        return util.deserialize_model(dikt, cls)

    @property
    def replicas_number(self) -> int:
        """Gets the replicas_number of this ScaleHorizontal.


        :return: The replicas_number of this ScaleHorizontal.
        :rtype: int
        """
        return self._replicas_number

    @replicas_number.setter
    def replicas_number(self, replicas_number: int):
        """Sets the replicas_number of this ScaleHorizontal.


        :param replicas_number: The replicas_number of this ScaleHorizontal.
        :type replicas_number: int
        """
        if replicas_number is None:
            raise ValueError("Invalid value for `replicas_number`, must not be `None`")  # noqa: E501

        self._replicas_number = replicas_number
