# coding: utf-8

# flake8: noqa

"""
    Edge-API

    The Edge-API is built under the BIND5G project and its purpose is to act as an intermidiator between the NaaS API and the Kubernetes cluster. The NaaS API is a general API in respect of the project to remotely and automatically deploy, manage and control 5G and MEC infrastructures for a vast amount of experiments. On the other hand, the Edge-API is a specific backend API to manage Kubernetes resources and deploy application instances into the cluster.  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: mdalgitsis@vicomtech.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.kubernetes_network_service_api import KubernetesNetworkServiceApi
from swagger_client.api.cluster_api import ClusterApi
from swagger_client.api.namespaces_api import NamespacesApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.deployment import Deployment
from swagger_client.models.kns import KNS
from swagger_client.models.kns_day2_actions import KNSDay2Actions
from swagger_client.models.limit_range import LimitRange
from swagger_client.models.namespace import Namespace
from swagger_client.models.pod import Pod
from swagger_client.models.resource_quota import ResourceQuota
from swagger_client.models.scale_horizontal import ScaleHorizontal
from swagger_client.models.scale_vertical import ScaleVertical
from swagger_client.models.service import Service
from swagger_client.models.service_monitor import ServiceMonitor
