# coding: utf-8

"""
    Edge-API

    The Edge-API is built under the BIND5G project and its purpose is to act as an intermidiator between the NaaS API and the Kubernetes cluster. The NaaS API is a general API in respect of the project to remotely and automatically deploy, manage and control 5G and MEC infrastructures for a vast amount of experiments. On the other hand, the Edge-API is a specific backend API to manage Kubernetes resources and deploy application instances into the cluster.  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: mdalgitsis@vicomtech.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResourceQuota(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resourcequota_name': 'str',
        'cpu_limit_value': 'str',
        'memory_limit_value': 'str',
        'cpu_request_value': 'str',
        'memory_request_value': 'str',
        'storage_request_value': 'str'
    }

    attribute_map = {
        'resourcequota_name': 'resourcequota_name',
        'cpu_limit_value': 'cpu_limit_value',
        'memory_limit_value': 'memory_limit_value',
        'cpu_request_value': 'cpu_request_value',
        'memory_request_value': 'memory_request_value',
        'storage_request_value': 'storage_request_value'
    }

    def __init__(self, resourcequota_name=None, cpu_limit_value=None, memory_limit_value=None, cpu_request_value=None, memory_request_value=None, storage_request_value=None):  # noqa: E501
        """ResourceQuota - a model defined in Swagger"""  # noqa: E501
        self._resourcequota_name = None
        self._cpu_limit_value = None
        self._memory_limit_value = None
        self._cpu_request_value = None
        self._memory_request_value = None
        self._storage_request_value = None
        self.discriminator = None
        self.resourcequota_name = resourcequota_name
        self.cpu_limit_value = cpu_limit_value
        self.memory_limit_value = memory_limit_value
        if cpu_request_value is not None:
            self.cpu_request_value = cpu_request_value
        if memory_request_value is not None:
            self.memory_request_value = memory_request_value
        if storage_request_value is not None:
            self.storage_request_value = storage_request_value

    @property
    def resourcequota_name(self):
        """Gets the resourcequota_name of this ResourceQuota.  # noqa: E501


        :return: The resourcequota_name of this ResourceQuota.  # noqa: E501
        :rtype: str
        """
        return self._resourcequota_name

    @resourcequota_name.setter
    def resourcequota_name(self, resourcequota_name):
        """Sets the resourcequota_name of this ResourceQuota.


        :param resourcequota_name: The resourcequota_name of this ResourceQuota.  # noqa: E501
        :type: str
        """
        if resourcequota_name is None:
            raise ValueError("Invalid value for `resourcequota_name`, must not be `None`")  # noqa: E501

        self._resourcequota_name = resourcequota_name

    @property
    def cpu_limit_value(self):
        """Gets the cpu_limit_value of this ResourceQuota.  # noqa: E501


        :return: The cpu_limit_value of this ResourceQuota.  # noqa: E501
        :rtype: str
        """
        return self._cpu_limit_value

    @cpu_limit_value.setter
    def cpu_limit_value(self, cpu_limit_value):
        """Sets the cpu_limit_value of this ResourceQuota.


        :param cpu_limit_value: The cpu_limit_value of this ResourceQuota.  # noqa: E501
        :type: str
        """
        if cpu_limit_value is None:
            raise ValueError("Invalid value for `cpu_limit_value`, must not be `None`")  # noqa: E501

        self._cpu_limit_value = cpu_limit_value

    @property
    def memory_limit_value(self):
        """Gets the memory_limit_value of this ResourceQuota.  # noqa: E501


        :return: The memory_limit_value of this ResourceQuota.  # noqa: E501
        :rtype: str
        """
        return self._memory_limit_value

    @memory_limit_value.setter
    def memory_limit_value(self, memory_limit_value):
        """Sets the memory_limit_value of this ResourceQuota.


        :param memory_limit_value: The memory_limit_value of this ResourceQuota.  # noqa: E501
        :type: str
        """
        if memory_limit_value is None:
            raise ValueError("Invalid value for `memory_limit_value`, must not be `None`")  # noqa: E501

        self._memory_limit_value = memory_limit_value

    @property
    def cpu_request_value(self):
        """Gets the cpu_request_value of this ResourceQuota.  # noqa: E501


        :return: The cpu_request_value of this ResourceQuota.  # noqa: E501
        :rtype: str
        """
        return self._cpu_request_value

    @cpu_request_value.setter
    def cpu_request_value(self, cpu_request_value):
        """Sets the cpu_request_value of this ResourceQuota.


        :param cpu_request_value: The cpu_request_value of this ResourceQuota.  # noqa: E501
        :type: str
        """

        self._cpu_request_value = cpu_request_value

    @property
    def memory_request_value(self):
        """Gets the memory_request_value of this ResourceQuota.  # noqa: E501


        :return: The memory_request_value of this ResourceQuota.  # noqa: E501
        :rtype: str
        """
        return self._memory_request_value

    @memory_request_value.setter
    def memory_request_value(self, memory_request_value):
        """Sets the memory_request_value of this ResourceQuota.


        :param memory_request_value: The memory_request_value of this ResourceQuota.  # noqa: E501
        :type: str
        """

        self._memory_request_value = memory_request_value

    @property
    def storage_request_value(self):
        """Gets the storage_request_value of this ResourceQuota.  # noqa: E501


        :return: The storage_request_value of this ResourceQuota.  # noqa: E501
        :rtype: str
        """
        return self._storage_request_value

    @storage_request_value.setter
    def storage_request_value(self, storage_request_value):
        """Sets the storage_request_value of this ResourceQuota.


        :param storage_request_value: The storage_request_value of this ResourceQuota.  # noqa: E501
        :type: str
        """

        self._storage_request_value = storage_request_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResourceQuota, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourceQuota):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
