# coding: utf-8

"""
    Edge-API

    The Edge-API is built under the BIND5G project and its purpose is to act as an intermidiator between the NaaS API and the Kubernetes cluster. The NaaS API is a general API in respect of the project to remotely and automatically deploy, manage and control 5G and MEC infrastructures for a vast amount of experiments. On the other hand, the Edge-API is a specific backend API to manage Kubernetes resources and deploy application instances into the cluster.  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: mdalgitsis@vicomtech.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ScaleHorizontal(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'replicas_number': 'int'
    }

    attribute_map = {
        'replicas_number': 'replicas_number'
    }

    def __init__(self, replicas_number=None):  # noqa: E501
        """ScaleHorizontal - a model defined in Swagger"""  # noqa: E501
        self._replicas_number = None
        self.discriminator = None
        self.replicas_number = replicas_number

    @property
    def replicas_number(self):
        """Gets the replicas_number of this ScaleHorizontal.  # noqa: E501


        :return: The replicas_number of this ScaleHorizontal.  # noqa: E501
        :rtype: int
        """
        return self._replicas_number

    @replicas_number.setter
    def replicas_number(self, replicas_number):
        """Sets the replicas_number of this ScaleHorizontal.


        :param replicas_number: The replicas_number of this ScaleHorizontal.  # noqa: E501
        :type: int
        """
        if replicas_number is None:
            raise ValueError("Invalid value for `replicas_number`, must not be `None`")  # noqa: E501

        self._replicas_number = replicas_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScaleHorizontal, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScaleHorizontal):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
