# coding: utf-8

"""
    Edge-API

    The Edge-API is built under the BIND5G project and its purpose is to act as an intermidiator between the NaaS API and the Kubernetes cluster. The NaaS API is a general API in respect of the project to remotely and automatically deploy, manage and control 5G and MEC infrastructures for a vast amount of experiments. On the other hand, the Edge-API is a specific backend API to manage Kubernetes resources and deploy application instances into the cluster.  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: mdalgitsis@vicomtech.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.namespaces_api import NamespacesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNamespacesApi(unittest.TestCase):
    """NamespacesApi unit test stubs"""

    def setUp(self):
        self.api = NamespacesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_namespace(self):
        """Test case for add_namespace

        Create a Namespace  # noqa: E501
        """
        pass

    def test_add_namespaced_deployment(self):
        """Test case for add_namespaced_deployment

        Create a Deployment in a specific namespace  # noqa: E501
        """
        pass

    def test_add_namespaced_limit_range(self):
        """Test case for add_namespaced_limit_range

        Create a LimitRange in a specific namespace  # noqa: E501
        """
        pass

    def test_add_namespaced_pod(self):
        """Test case for add_namespaced_pod

        Create a Pod in a Namespace  # noqa: E501
        """
        pass

    def test_add_namespaced_resource_quota(self):
        """Test case for add_namespaced_resource_quota

        Create a ResourceQuota in a specific namespace  # noqa: E501
        """
        pass

    def test_add_namespaced_service(self):
        """Test case for add_namespaced_service

        Create a Service in a specific namespace  # noqa: E501
        """
        pass

    def test_add_namespaced_service_monitor(self):
        """Test case for add_namespaced_service_monitor

        Create a ServiceMonitor in a specific namespace  # noqa: E501
        """
        pass

    def test_delete_namespace(self):
        """Test case for delete_namespace

        Delete a Namespace  # noqa: E501
        """
        pass

    def test_delete_namespaced_deployment(self):
        """Test case for delete_namespaced_deployment

        Delete a namespaced Deployment  # noqa: E501
        """
        pass

    def test_delete_namespaced_limit_range(self):
        """Test case for delete_namespaced_limit_range

        Delete a namespaced LimitRange  # noqa: E501
        """
        pass

    def test_delete_namespaced_pod(self):
        """Test case for delete_namespaced_pod

        Delete a Pod from a specific Namespace  # noqa: E501
        """
        pass

    def test_delete_namespaced_resource_quota(self):
        """Test case for delete_namespaced_resource_quota

        Delete a namespaced ResourceQuota  # noqa: E501
        """
        pass

    def test_delete_namespaced_service(self):
        """Test case for delete_namespaced_service

        Delete a namespaced Service  # noqa: E501
        """
        pass

    def test_delete_namespaced_service_monitor(self):
        """Test case for delete_namespaced_service_monitor

        Delete a namespaced ServiceMonitor  # noqa: E501
        """
        pass

    def test_get_namespaced_deployment(self):
        """Test case for get_namespaced_deployment

        Read a namespaced Deployment definition  # noqa: E501
        """
        pass

    def test_get_namespaced_deployment_resources(self):
        """Test case for get_namespaced_deployment_resources

        Read namespaced Deployment resources  # noqa: E501
        """
        pass

    def test_get_namespaced_deployment_scale_replicas(self):
        """Test case for get_namespaced_deployment_scale_replicas

        Read namespaced Deployment Scale replicas  # noqa: E501
        """
        pass

    def test_get_namespaced_deployment_status(self):
        """Test case for get_namespaced_deployment_status

        Read namespaced Deployment status  # noqa: E501
        """
        pass

    def test_get_namespaced_deployments(self):
        """Test case for get_namespaced_deployments

        List Deployments of a specific Namespace  # noqa: E501
        """
        pass

    def test_get_namespaced_limit_range(self):
        """Test case for get_namespaced_limit_range

        Read a namespaced LimitRange definition  # noqa: E501
        """
        pass

    def test_get_namespaced_limit_ranges(self):
        """Test case for get_namespaced_limit_ranges

        List LimitRanges by namespace  # noqa: E501
        """
        pass

    def test_get_namespaced_pod_logs(self):
        """Test case for get_namespaced_pod_logs

        Get logs of a namespaced Pod  # noqa: E501
        """
        pass

    def test_get_namespaced_pods(self):
        """Test case for get_namespaced_pods

        List Pods by Namespace  # noqa: E501
        """
        pass

    def test_get_namespaced_resource_quota(self):
        """Test case for get_namespaced_resource_quota

        Read a namespaced ResourceQuota definition  # noqa: E501
        """
        pass

    def test_get_namespaced_resource_quotas(self):
        """Test case for get_namespaced_resource_quotas

        List ResourceQuotas by namespace  # noqa: E501
        """
        pass

    def test_get_namespaced_service(self):
        """Test case for get_namespaced_service

        Read a namespaced Service definition  # noqa: E501
        """
        pass

    def test_get_namespaced_service_monitor(self):
        """Test case for get_namespaced_service_monitor

        Read a namespaced ServiceMonitor definition  # noqa: E501
        """
        pass

    def test_get_namespaced_service_monitors(self):
        """Test case for get_namespaced_service_monitors

        List ServiceMonitors by namespace  # noqa: E501
        """
        pass

    def test_get_namespaced_service_status(self):
        """Test case for get_namespaced_service_status

        Read namespaced Service status  # noqa: E501
        """
        pass

    def test_get_namespaced_services(self):
        """Test case for get_namespaced_services

        List Services by namespace  # noqa: E501
        """
        pass

    def test_get_namespaces(self):
        """Test case for get_namespaces

        List all Namespaces  # noqa: E501
        """
        pass

    def test_scale_horizontal_namespaced_deployment(self):
        """Test case for scale_horizontal_namespaced_deployment

        Scale Horizontal a namespaced Deployment  # noqa: E501
        """
        pass

    def test_scale_vertical_namespaced_deployment(self):
        """Test case for scale_vertical_namespaced_deployment

        Scale Vertical a namespaced Deployment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
