# coding: utf-8

"""
    Edge-API

    The Edge-API is built under the BIND5G project and its purpose is to act as an intermidiator between the NaaS API and the Kubernetes cluster. The NaaS API is a general API in respect of the project to remotely and automatically deploy, manage and control 5G and MEC infrastructures for a vast amount of experiments. On the other hand, the Edge-API is a specific backend API to manage Kubernetes resources and deploy application instances into the cluster.  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: mdalgitsis@vicomtech.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.kubernetes_network_service_api import KubernetesNetworkServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestKubernetesNetworkServiceApi(unittest.TestCase):
    """KubernetesNetworkServiceApi unit test stubs"""

    def setUp(self):
        self.api = KubernetesNetworkServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_kns(self):
        """Test case for add_kns

        Create a Kubernetes Network Service  # noqa: E501
        """
        pass

    def test_delete_kns(self):
        """Test case for delete_kns

        Delete a Kubernetes Network Service  # noqa: E501
        """
        pass

    def test_get_all_kns(self):
        """Test case for get_all_kns

        List Kubernetes Network Services  # noqa: E501
        """
        pass

    def test_get_kns(self):
        """Test case for get_kns

        Get a Kubernetes Network Service  # noqa: E501
        """
        pass

    def test_update_kns(self):
        """Test case for update_kns

        Day2Actions in a Kubernetes Network Service  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
