# coding: utf-8

"""
    Edge-API

    The Edge-API is built under the BIND5G project and its purpose is to act as an intermidiator between the NaaS API and the Kubernetes cluster. The NaaS API is a general API in respect of the project to remotely and automatically deploy, manage and control 5G and MEC infrastructures for a vast amount of experiments. On the other hand, the Edge-API is a specific backend API to manage Kubernetes resources and deploy application instances into the cluster.  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: mdalgitsis@vicomtech.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cluster_api import ClusterApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClusterApi(unittest.TestCase):
    """ClusterApi unit test stubs"""

    def setUp(self):
        self.api = ClusterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_deployments(self):
        """Test case for get_all_deployments

        List Deployments for all Namespaces  # noqa: E501
        """
        pass

    def test_get_all_limit_ranges(self):
        """Test case for get_all_limit_ranges

        List LimitRanges for all Namespaces  # noqa: E501
        """
        pass

    def test_get_all_pods(self):
        """Test case for get_all_pods

        List Pods for all Namespaces  # noqa: E501
        """
        pass

    def test_get_all_resource_quotas(self):
        """Test case for get_all_resource_quotas

        List ResourceQuotas for all Namespaces  # noqa: E501
        """
        pass

    def test_get_all_service_monitors(self):
        """Test case for get_all_service_monitors

        List ServiceMonitors for all Namespaces  # noqa: E501
        """
        pass

    def test_get_all_services(self):
        """Test case for get_all_services

        List Services for all Namespaces  # noqa: E501
        """
        pass

    def test_get_node_status(self):
        """Test case for get_node_status

        Get a specific Node  # noqa: E501
        """
        pass

    def test_get_nodes(self):
        """Test case for get_nodes

        List the existing Nodes of the cluster  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
